### PR TITLE
Fix for #83: Integrated devonfw maven-parent as parent pom.xml

### PR DESCRIPTION
**Pull request by lmarniazman**
Fix for #83

### CODE REVIEW

**Comment by lmarniazman** [comment]
I updated the PR as to your first two points, but I'm not sure what you mean exactly with the third point. Should we have an extra pom.xml in this repository for documentation and include docgen as a dependency there, like it is in devon4j?

**Comment by lmarniazman** [comment]
Also, since the new devon4j version is out now, we should update the used version here too. Is it fine if I add it in this PR or should I create a seperate one?

**Comment by hohwille** [comment]
> but I'm not sure what you mean exactly with the third point. Should we have an extra pom.xml in this repository for documentation and include docgen as a dependency there, like it is in devon4j?

Indeed we do not yet have a `documentation` folder in this repo. So in that case I will delete the 3rd point as it does not make sense. We can introduce this documentation but not as part of this PR.

**Comment by hohwille** [comment]
> Also, since the new devon4j version is out now, we should update the used version here too. Is it fine if I add it in this PR or should I create a seperate one?

Right. You can include this change into this PR. I will already approve now. Thanks for your work 👍

**Pull request merged**
