### PR TITLE
Updated dependencies to solve failing tests

### PR DESCRIPTION
**Pull request by lmarniazman**
Fix for #48 & #44

### CODE REVIEW

**Comment by lmarniazman** [comment]
The changes in PR #47 are also from this branch, I just merged it into the branch from #47. This JavaCheckVerifier error occurred on all branches once I switched to the new beta25 ide, so I made those changes in all my branches so I wouldn't have any problems with the tests.

**Comment by lmarniazman** [comment]
So basically, what this PR contains is updated dependencies (already in PR #47), and a refactoring of the getFile() method from the JavaFileScannerContext, because it is deprecated.

**Comment by hohwille** [comment]
I think this PR is somehow messed. As even the title does not match anymore and it has conflicts, I rather close it. If that `getFile()` changes are still relevant, can you open a new PR from that? Thank you so much.

**Comment by lmarniazman** [comment]
Sure, I will open a new issue and corresponding PR.

**Pull request closed without merging**
